### ISSUE TITLE
メッセージ投稿機能を実装

### ISSUE THREAD

**Issue by y0shihiro** [Variableavalanchezueha/chat#13]
## 何故やりたいのか・解決したい課題（Why）
- コミュニティの場を作る
## 解決する方法・手段（How）
- ユーザー同士でメッセージを投稿しあって会話をする
## なに（What）をつくるのか？
- メッセージを投稿する機能
## どうやって（How）つくるのか？
- メッセージトップ画面でメッセージ投稿フォームを作る

スケジュール
１月１１日（土）予定

**Comment by y0shihiro** [comment]
### 投稿の文字数制限は何文字にしましょうか？
参考
- Twitter　140

- Instagram　2200


- LINE　1万

**Comment by namida-neet** [comment]
50文字はどうでしょうか？この文章がちょうど50文字です。50文字はこれくらいです。どうでしょうか。

**Comment by y0shihiro** [comment]
50文字で決定！
