### ISSUE TITLE
ログイン、サインアップで成功or失敗したときに何もメッセージでない

### ISSUE THREAD

**Issue by y0shihiro** [Variableavalanchezueha/chat#14]
## 不具合の詳細
- ログインで成功or失敗したときに何もメッセージでない
- サインアップで成功or失敗したときに何もメッセージでない

## 再現手順

1. ログイン画面でusername、passwordを入力
2. ログインボタンをクリックする

1. ユーザー登録画面でusername、passwordを入力
2. サインアップボタンをクリックする

## OSやバージョン
- 

## 発生時期
- １月５日　ユーザー登録、ログイン機能確認時

**Comment by namida-neet** [comment]
fix番号ってやるとプルリクエストに連動してイシュ〜も閉じるんですね。知りませんでした。勉強になりました。手動で閉じます。
